import { CaptionStyle, StylePreset } from "../types";

export const BUNDLED_FONTS_GROUPED: Record<string, { name: string; value: string }[]> = {
  "Sinhala — Modern": [
    { name: "Noto Sans Sinhala (Modern Sinhala)", value: "Noto Sans Sinhala" },
    { name: "Gemunu Libre", value: "Gemunu Libre" },
    { name: "Maname", value: "Maname" },
    { name: "Yaldevi", value: "Yaldevi" }
  ],
  "Sinhala — Elegant/Serif": [
    { name: "Abhaya Libre (Elegant Sinhala)", value: "Abhaya Libre" },
    { name: "Noto Serif Sinhala (Classic Sinhala)", value: "Noto Serif Sinhala" }
  ],
  "Sinhala — Bold Display": [
    { name: "AF Sandarenu", value: "AF Sandarenu" },
    { name: "AF Sigiri", value: "AF Sigiri" },
    { name: "Aloka", value: "Aloka" },
    { name: "Anupama", value: "Anupama" },
    { name: "Aragalaya", value: "Aragalaya" },
    { name: "Arana", value: "Arana" },
    { name: "Fontoshan", value: "Fontoshan" },
    { name: "Mihiravi", value: "Mihiravi" },
    { name: "Pawana", value: "Pawana" },
    { name: "Pradeep", value: "Pradeep" },
    { name: "Yatra One (Retro Sinhala)", value: "Yatra One" }
  ],
  "Sinhala — Handwritten": [
    { name: "Tharu Malee", value: "Tharu Malee" },
    { name: "Tharu Nidahasa", value: "Tharu Nidahasa" },
    { name: "Tharu Nikini", value: "Tharu Nikini" },
    { name: "Tharu Sansala", value: "Tharu Sansala" },
    { name: "Tharu", value: "Tharu" }
  ],
  "Sinhala — Numbered/Misc": [
    { name: "SN01", value: "SN01" },
    { name: "SN02", value: "SN02" },
    { name: "SN03", value: "SN03" },
    { name: "SN04", value: "SN04" },
    { name: "SN05", value: "SN05" },
    { name: "SN06", value: "SN06" },
    { name: "SN07", value: "SN07" },
    { name: "SN08", value: "SN08" },
    { name: "SN09", value: "SN09" },
    { name: "SN10", value: "SN10" },
    { name: "SN11", value: "SN11" },
    { name: "SN12", value: "SN12" },
    { name: "SN13", value: "SN13" },
    { name: "SN14", value: "SN14" },
    { name: "SN15", value: "SN15" },
    { name: "SN16", value: "SN16" },
    { name: "SN17", value: "SN17" },
    { name: "SN18", value: "SN18" },
    { name: "SN19", value: "SN19" },
    { name: "SN20", value: "SN20" },
    { name: "SN21", value: "SN21" }
  ],
  "English — Bold Display": [
    { name: "Impact (Bold Memes)", value: "Impact" },
    { name: "Anton", value: "Anton" },
    { name: "Archivo Black", value: "Archivo Black" },
    { name: "Bebas Neue", value: "Bebas Neue" },
    { name: "Blaak", value: "Blaak" },
    { name: "Cc Oldpress", value: "Cc Oldpress" },
    { name: "Coolvetica", value: "Coolvetica" },
    { name: "Larken Bold", value: "Larken Bold" },
    { name: "Lemon Milk", value: "Lemon Milk" },
    { name: "Montserrat Extrabold", value: "Montserrat Extrabold" },
    { name: "Neogen Black", value: "Neogen Black" },
    { name: "Tactic Sans", value: "Tactic Sans" },
    { name: "Wark", value: "Wark" }
  ],
  "English — Clean/Sans": [
    { name: "Inter (Minimalist Clean)", value: "Inter" },
    { name: "Space Grotesk (Tech Display)", value: "Space Grotesk" },
    { name: "JetBrains Mono (Technical)", value: "JetBrains Mono" },
    { name: "Inter Extrabold", value: "Inter Extrabold" },
    { name: "Manrope", value: "Manrope" },
    { name: "Monofonto", value: "Monofonto" },
    { name: "Montserrat", value: "Montserrat" },
    { name: "Noto Sans Bold", value: "Noto Sans Bold" },
    { name: "Open Sauce", value: "Open Sauce" },
    { name: "Poppins", value: "Poppins" },
    { name: "Oswald", value: "Oswald" }
  ],
  "English — Handwritten/Script": [
    { name: "Adelia", value: "Adelia" },
    { name: "Autography", value: "Autography" },
    { name: "Caveat", value: "Caveat" },
    { name: "Gentle Hearts", value: "Gentle Hearts" },
    { name: "Glorida", value: "Glorida" },
    { name: "Kids Word", value: "Kids Word" },
    { name: "Leslies Hand", value: "Leslies Hand" },
    { name: "Lost Hand", value: "Lost Hand" },
    { name: "Watch Sunset", value: "Watch Sunset" }
  ]
};

export const BUNDLED_FONTS = Object.values(BUNDLED_FONTS_GROUPED).flat();

export const DEFAULT_STYLE: CaptionStyle = {
  fontFamily: "Noto Sans Sinhala",
  fontSize: 26,
  letterSpacing: 0,
  lineHeight: 1.3,
  textColor: "#FFFFFF",
  activeColor: "#FACC15", // yellow-400
  outlineColor: "#000000",
  outlineWidth: 0,
  shadowColor: "rgba(0,0,0,0.5)",
  shadowBlur: 4,
  shadowOffsetX: 2,
  shadowOffsetY: 2,
  background: "none",
  backgroundColor: "#000000",
  backgroundOpacity: 0.65,
  textTransform: "none",
  position: "bottom",
  verticalOffset: 0,
  animationStyle: "karaoke",
};

export const STYLE_PRESETS: StylePreset[] = [
  {
    name: "Bold Karaoke 🎤",
    description: "High-contrast thick outlines with active yellow word fill swipe.",
    style: {
      fontFamily: "Noto Sans Sinhala",
      fontSize: 28,
      textColor: "#FFFFFF",
      activeColor: "#FFDD00",
      outlineColor: "#000000",
      outlineWidth: 4,
      background: "none",
      animationStyle: "karaoke",
    },
  },
  {
    name: "Minimal Clean ✨",
    description: "Simple clean typography with soft translucent background pill and fade in.",
    style: {
      fontFamily: "Inter",
      fontSize: 22,
      textColor: "#FFFFFF",
      activeColor: "#FFFFFF",
      outlineColor: "#000000",
      outlineWidth: 0,
      background: "pill",
      backgroundColor: "#000000",
      backgroundOpacity: 0.5,
      animationStyle: "fade",
    },
  },
  {
    name: "Big Bounce 🚀",
    description: "Thick playful captions with individual letters jumping up on speaking.",
    style: {
      fontFamily: "Impact",
      fontSize: 32,
      textColor: "#FFFFFF",
      activeColor: "#22C55E", // green-500
      outlineColor: "#000000",
      outlineWidth: 4,
      background: "none",
      animationStyle: "bounce",
    },
  },
  {
    name: "TikTok Word 🔥",
    description: "TikTok/Reels style: Single large centered word popping on beat.",
    style: {
      fontFamily: "Space Grotesk",
      fontSize: 42,
      textColor: "#FFFFFF",
      activeColor: "#FF007F", // bright magenta
      outlineColor: "#000000",
      outlineWidth: 5,
      background: "pill",
      backgroundColor: "#000000",
      backgroundOpacity: 0.8,
      position: "center",
      animationStyle: "centeredWord",
    },
  },
  {
    name: "Retro Glow 📻",
    description: "Vintage aesthetics with a warm orange glow and soft slides.",
    style: {
      fontFamily: "Yatra One",
      fontSize: 26,
      textColor: "#E5E7EB",
      activeColor: "#F97316", // orange-500
      outlineColor: "#451A03",
      outlineWidth: 2,
      background: "none",
      animationStyle: "glow",
    },
  },
  {
    name: "Bold Pop 💥",
    description: "Punchy bold text with a pop/scale-in animation on each word.",
    style: {
      fontFamily: "Montserrat Extrabold",
      fontSize: 30,
      textColor: "#FFFFFF",
      activeColor: "#3B82F6", // blue-500
      outlineColor: "#000000",
      outlineWidth: 3,
      background: "none",
      animationStyle: "pop",
    },
  },
  {
    name: "Silver Glow 🥈",
    description: "Cool grey/silver text with a soft white/silver outer glow.",
    style: {
      fontFamily: "Inter",
      fontSize: 25,
      textColor: "#D1D5DB",
      activeColor: "#F3F4F6",
      outlineColor: "#1F2937",
      outlineWidth: 2,
      shadowColor: "#FFFFFF",
      shadowBlur: 10,
      background: "none",
      animationStyle: "glow",
    },
  },
  {
    name: "Spring Bounce 🤸",
    description: "Bouncy vertical spring animation per word as it's spoken.",
    style: {
      fontFamily: "Lemon Milk",
      fontSize: 28,
      textColor: "#FFFFFF",
      activeColor: "#FACC15",
      outlineColor: "#111827",
      outlineWidth: 3,
      background: "none",
      animationStyle: "bounce",
    },
  },
  {
    name: "TikTok Bold 📱",
    description: "Big bold social caption text, centered word popping style.",
    style: {
      fontFamily: "Inter Extrabold",
      fontSize: 36,
      textColor: "#FFFFFF",
      activeColor: "#FF007F",
      outlineColor: "#000000",
      outlineWidth: 4,
      background: "none",
      animationStyle: "centeredWord",
    },
  },
  {
    name: "Underline Pop ✍️",
    description: "Active word gets an animated underline and text pop effect.",
    style: {
      fontFamily: "Abhaya Libre",
      fontSize: 28,
      textColor: "#FFFFFF",
      activeColor: "#F59E0B",
      outlineColor: "#000000",
      outlineWidth: 1,
      background: "none",
      animationStyle: "underlinePop",
    },
  },
  {
    name: "Metallic Gold 👑",
    description: "Luxury gold gradient fill with premium pop-in animation.",
    isPro: true,
    style: {
      fontFamily: "Montserrat Extrabold",
      fontSize: 30,
      textColor: "#E5E7EB",
      activeColor: "#FFD700",
      textFillType: "gradient-gold",
      outlineColor: "#000000",
      outlineWidth: 3,
      background: "none",
      animationStyle: "pop",
    },
  },
  {
    name: "Chrome Steel ⚡",
    description: "Sleek chrome/silver gradient fill with smooth typewriter effect.",
    isPro: true,
    style: {
      fontFamily: "Anton",
      fontSize: 32,
      textColor: "#9CA3AF",
      activeColor: "#FFFFFF",
      textFillType: "gradient-chrome",
      outlineColor: "#111827",
      outlineWidth: 3,
      background: "none",
      animationStyle: "zoom",
    },
  },
  {
    name: "Neon Glow 🔮",
    description: "Vibrant saturated neon sign look with layered outer glow passes.",
    isPro: true,
    style: {
      fontFamily: "Bebas Neue",
      fontSize: 34,
      textColor: "#FFFFFF",
      activeColor: "#39FF14", // neon green
      outlineColor: "#003300",
      outlineWidth: 2,
      background: "none",
      animationStyle: "neonGlow",
    },
  },
  {
    name: "Digital Glitch 👾",
    description: "Retro cyberpunk style with split cyan/red duplicate offsets.",
    isPro: true,
    style: {
      fontFamily: "Fira Code",
      fontSize: 28,
      textColor: "#FFFFFF",
      activeColor: "#00FFFF",
      outlineColor: "#111827",
      outlineWidth: 2,
      background: "none",
      animationStyle: "glitch",
    },
  },
  {
    name: "Light Sweep 🌠",
    description: "Diagonal linear light sweep passing across the active word.",
    isPro: true,
    style: {
      fontFamily: "Space Grotesk",
      fontSize: 30,
      textColor: "#FFFFFF",
      activeColor: "#6366F1", // indigo-500
      outlineColor: "#000000",
      outlineWidth: 3,
      background: "none",
      animationStyle: "lightSweep",
    },
  },
];
